Desktop version
deniodev/Personal-Portfolio pull request #4
Opened 2023-03-31 11:37 UTC by deniodev

2023-03-31 13:47 UTC, didierganthier requested changes
Hi @deniodev ,

🎉 Good job so far! You're making great progress on this project, but there are still a few areas that need attention before we can move on to the next step.

<img src="https://media.giphy.com/media/3oEduMcvxTNPlGuhH2/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Required Changes 🛠
- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-03-31 13:47 UTC, didierganthier commented on index.html
> +            </div>
Nice having a featured section 👍🏽 but make sure to adjust the spacing and the sizes of the elements, it's not looking quite right yet on several screen sizes 👀  take a look at the differences:

## Your design

![Screenshot 2023-03-31 at 09 06 14](https://user-images.githubusercontent.com/45739963/229128041-816090c1-f636-442b-a577-5135d65efbed.png)

## Figma

![Screenshot 2023-03-31 at 09 06 35](https://user-images.githubusercontent.com/45739963/229128104-a3987e38-dd02-456b-bfaf-779db970f069.png)

As you can notice, the featured image 🖼️ should be taking much more space (60% of the width) and the rest should be taking (40%) while being aligned to the left ◀️, make sure to adjust that along with the spacing between the elements such as the list of technologies 🤔 also the heading of the featured project should come first and the font size should be bigger than the following text in the section. 🤓

2023-03-31 13:47 UTC, didierganthier commented on index.html
> +              </div>
The cards look nice 💯 but they need to be spaced better, the container of your cards has too much spacing or maybe your cards don't take enough space 🤔 this is what you're supposed to have 👇🏽 

![Screenshot 2023-03-31 at 09 21 35](https://user-images.githubusercontent.com/45739963/229131486-1aafedae-d254-49c6-a030-c72fcdbd65a8.png)

This is what you have on full-screen size 👇🏽 

![Screenshot 2023-03-31 at 09 23 00](https://user-images.githubusercontent.com/45739963/229131870-54a342eb-4701-45d5-9886-0b89f8a308ca.png)

Make sure to also adjust the spacing of the elements inside of each card right now 👁️ last thing but not least, I also noticed that you designed the first one differently (just like it looks in the Figma )

![Screenshot 2023-03-31 at 09 31 20](https://user-images.githubusercontent.com/45739963/229133754-64e2920d-8f7e-4904-8c94-085a2fc008bd.png)

 but the goal of the Figma when making the first design different was to showcase how the card should look when the mouse goes over it (hover effect) 🤓 so keep that design in mind and just adjust it to make all cards look like that but only when they're hovered. If you have any questions about this or if my explanation is a bit confusing, feel free to tag me. 😉

2023-03-31 13:47 UTC, didierganthier commented on index.html
> +        </footer>
Good looking social icons 😻 I love how aligned they are but I feel like their container is too big at the moment, it makes them look too small. Take a look at what the Figma has 👇🏽 

![Screenshot 2023-03-31 at 09 40 31](https://user-images.githubusercontent.com/45739963/229135858-ec0fdbeb-8397-4c30-ab8e-46da6a51335f.png)

And this is what you have so far 👇🏽 

![Screenshot 2023-03-31 at 09 40 52](https://user-images.githubusercontent.com/45739963/229135953-df5d7a2f-246e-46b7-9e1a-66ffc6c76df2.png)

Did I lie? 🤔 I didn't think so 😄 and I believe you can easily adjust that 💪🏽

2023-03-31 13:47 UTC, didierganthier commented on index.html
>              </p>
It's good learning a bit about you 🤝 but to make this section even more enjoyable to read, after the Section's Title, also aligned to the left there should be 4 to 5 lines of text describing your experience. Your text is only taking two lines for now on full-screen size, you could perhaps adjust that by trapping it inside a box/container. 🤔  Take a look 👇🏽 

![Screenshot 2023-03-31 at 09 46 19](https://user-images.githubusercontent.com/45739963/229137304-16931bd5-2bff-473d-b9a7-4ecfdaa4b1ff.png)

2023-04-01 14:18 UTC, deniodev commented
Hi @didierganthier 
Good day

Kindly see the requested changes done:
- Adjust the spacing and the sizes of the works section;
- Adjust the spacing and the sizes of the cards section;
- Add  hover effects on the cards section;
- Align the titles and icons on the skills section;
- Adjust the social media icons;
- Adjust the text in the About-me section;

2023-04-01 14:47 UTC, amon-cofie approved these changes
Hi @deniodev , 👋  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights

- Descriptive PR 🚀 
- Linters are passing 🚀 
- GitHub flow used properly 🚀 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 14:53 UTC, merged